### ISSUE TITLE
Crash when permission is denied

### ISSUE THREAD

**Issue by ArthurSav** [MaxCruz/reactive_permissions#2]
Crashes if i deny permissions

Stacktrace
`Caused by: com.fasterxml.jackson.databind.JsonMappingException: No suitable constructor found for type [simple type, class com.maxcruz.reactivePermissions.entity.Permission]: can not instantiate from JSON object (missing default constructor or creator, or perhaps need to add/enable type information?)
    at [Source: {"canContinue":true,"explanationResource":2131165298,"permission":"android.permission.ACCESS_FINE_LOCATION"}; line: 1, column: 2]
       at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1130)
       at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:298)
       at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:133)
       at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3807)
       at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2816)
       at com.maxcruz.reactivePermissions.ui.ExplainDialog.onViewCreated(ExplainDialog.kt:137)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:998)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1163)
       at android.app.BackStackRecord.run(BackStackRecord.java:793)
       at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1552)
       at android.app.FragmentController.execPendingActions(FragmentController.java:325)
       at android.app.Activity.performResume(Activity.java:6981)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4144)`

**Comment by maxcruz** [comment]
Thanks

It seems that is missing a default constructor in the data class Permission, but I can't reproduce the error. Could you give me details to fix it?

**Comment by ArthurSav** [comment]
I followed the default setup.
Hm, now that i think of it i'm also using proguard

**Comment by maxcruz** [comment]
This issue would be solved now because Jackson dependency was removed
